// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgg1v6rGLSpZjRvYhVmIM_4jRjFoFXoDo',
    appId: '1:93116857123:web:390521b5f3179c5cde2a96',
    messagingSenderId: '93116857123',
    projectId: 'authfirebaseapp-7aee5',
    authDomain: 'authfirebaseapp-7aee5.firebaseapp.com',
    storageBucket: 'authfirebaseapp-7aee5.firebasestorage.app',
    measurementId: 'G-NXP2R9DLRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9709OwayYobRtAwFnIFeRGi02QhLfpgo',
    appId: '1:93116857123:android:8985642856fde721de2a96',
    messagingSenderId: '93116857123',
    projectId: 'authfirebaseapp-7aee5',
    storageBucket: 'authfirebaseapp-7aee5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsA49K9gAOW54ZtXcy1LjmvdJE3EnY9A8',
    appId: '1:93116857123:ios:c471d51dd3200442de2a96',
    messagingSenderId: '93116857123',
    projectId: 'authfirebaseapp-7aee5',
    storageBucket: 'authfirebaseapp-7aee5.firebasestorage.app',
    iosBundleId: 'com.example.authFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsA49K9gAOW54ZtXcy1LjmvdJE3EnY9A8',
    appId: '1:93116857123:ios:c471d51dd3200442de2a96',
    messagingSenderId: '93116857123',
    projectId: 'authfirebaseapp-7aee5',
    storageBucket: 'authfirebaseapp-7aee5.firebasestorage.app',
    iosBundleId: 'com.example.authFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgg1v6rGLSpZjRvYhVmIM_4jRjFoFXoDo',
    appId: '1:93116857123:web:05963677eef4d30cde2a96',
    messagingSenderId: '93116857123',
    projectId: 'authfirebaseapp-7aee5',
    authDomain: 'authfirebaseapp-7aee5.firebaseapp.com',
    storageBucket: 'authfirebaseapp-7aee5.firebasestorage.app',
    measurementId: 'G-SZWQW49L8Y',
  );
}
